#ifndef DEF_MUSICXMLPAGE

#define DEF_MUSICXMLPAGE

// Error codes

#define		ERCODE_NONE									0
#define		ERCODE_COULD_NOT_LOAD_DLL					1
#define		ERCODE_DLL_IS_NOT_LOADED					2
#define		ERCODE_DLL_ALREADY_LOADED					3
#define		ERCODE_COULD_NOT_OPEN_FILE_FOR_READING		4
#define		ERCODE_FORMAT_ERROR_IN_PIZ_FILE				5
#define		ERCODE_COULD_NOT_OPEN_CHORD_LIBRARY			6
#define		ERCODE_COULD_NOT_OPEN_RESOURCE_FILE			7
#define		ERCODE_COULD_NOT_IMPORT_MIDI_FILE			8
#define		ERCODE_COULD_NOT_OPEN_TABLE_FONT			9
#define		ERCODE_COULD_NOT_IMPORT_MUSICXML_FILE		10
#define		ERCODE_INVALID_DOC_ID						11
#define		ERCODE_INVALID_TYPE_OF_FILE					12
#define		ERCODE_COULD_NOT_SAVE_PIZ_FILE				13
#define		ERCODE_COULD_NOT_SAVE_MID_FILE				14
#define		ERCODE_COULD_NOT_SAVE_XML_FILE				15
#define		ERCODE_COULD_NOT_CREATE_PDF_FILE			16
#define		ERCODE_NO_PAGE_LAYOUT_DEFINED				17
#define		ERCODE_IMPOSSIBLE_TO_CREATE_TEMP_FILE		18
#define		ERCODE_IMPOSSIBLE_TO_WRITE_TEMP_FILE		19
#define		ERCODE_BUFFER_TOO_SMALL						20
#define		ERCODE_IMPOSSIBLE_TO_OPEN_TEMP_FILE			21
#define		ERCODE_INVALID_PAGE_NUMBER					22
#define		ERCODE_INVALID_KEYSIG_INDEX					23
#define		ERCODE_INVALID_TIMESIG_INDEX				24
#define		ERCODE_INVALID_RANGE_OF_MEASURES			25
#define		ERCODE_ALREADY_PLAYING						26
#define		ERCODE_NO_SCORE_PLAYING						27
#define		ERCODE_INVALID_MIDI_PORT_INDEX				28
#define		ERCODE_MIDI_PORT_ALREADY_OPEN				29
#define		ERCODE_NO_MIDI_PORT_DEFINED					30
#define		ERCODE_STILL_PLAYING						31
#define		ERCODE_NO_MEASURES_IN_PAGE					32
#define		ERCODE_INVALID_STAFF_NUMBER					33
#define		ERCODE_INVALID_PARAMETER_NUMBER				34
#define		ERCODE_INVALID_PARAMETER_VALUE				35
#define		ERCODE_NO_SCORE_DISPLAYED					36
#define		ERCODE_POSITION_NOT_INSIDE_MEASURE			37
#define		ERCODE_KEYBOARD_ALREADY_DEFINED				38
#define		ERCODE_NO_KEYBOARD_DEFINED					39
#define		ERCODE_FRETBOARD_ALREADY_DEFINED			40
#define		ERCODE_NO_FRETBOARD_DEFINED					41
#define		ERCODE_LIBRARY_ALREADY_LOADED				42
#define		ERCODE_NO_LIBRARY_LOADED					43
#define		ERCODE_MIDI_RUNNING							44
#define		ERCODE_COULD_NOT_LOAD_LIBRARY				45
#define		ERCODE_INVALID_MODE_SPECIFICATION			46
#define		ERCODE_COULD_NOT_CREATE_AUDIO_FILE			47
#define		ERCODE_OUT_OF_MEMORY						48
#define		ERCODE_INVALID_INTERVAL_SPECIFICATION		49
#define		ERCODE_COULD_NOT_CREATE_DOCUMENT			50
#define		ERCODE_INVALID_MEASURE_NUMBER				51
#define		ERCODE_INVALID_OBJECT_INDEX					52
#define		ERCODE_INVALID_OBJECT						53
#define		ERCODE_INVALID_LYRIC_LINE_NUMBER			54
#define		ERCODE_INVALID_CHORD_INDEX					55
#define		ERCODE_INVALID_MIDIEVENT_INDEX				56
#define		ERCODE_INTERNAL_ERROR						57
#define		ERCODE_INVALID_RANGE_OF_STAVES				58
#define		ERCODE_INVALID_SYSTEM_NUMBER				59
#define		ERCODE_INVALID_SDK_LICENCE					60
#define		ERCODE_MNL_ALREADY_LOADED					61
#define		ERCODE_MNL_NOT_LOADED						62


class musicxmlpage
{

public:
	musicxmlpage(HWND lhWnd , HMODULE myDLL);
	~musicxmlpage();

	bool isOK();

	bool setFile(const char*fileName);

	void setScalefactor(float f);
	int setBarNr(long n);
	void drawPage();
	void onSize();

private:
	HMODULE mDll;
	// Handle to the main window and device context and application
	HWND 			hWnd;

	long docID;
	long barNr, nbBar, padding ;
	long width, height;
	float scalefactor;

	int status;

};

#endif